== Use Cases

=== Use a Survey

As a first exercise let's see how a Job Template Survey will show up in the Self-Service Portal. Again we won't provide step-by-step instructions but just the outline what you have to do:

* As admin user in AAP, add a Survey to the duplicated Job Template user1 is allowed to execute
* There is not a lot of sensible things you could add here to the demo Playbook, this is just for learning purposes
* E.g. add a Survey that provides some multiple-choice options... whatever suits you ;-)
* Don't forget to enable the Survey

Now in the Self-Service Portal as user admin resync the Job Templates again.

[NOTE]
====
The Self-Service Portal syncs users and other entities on a regular, configurable schedule. To speed things up we do this manually here
====

If you now run the Job Template in Self-Service Portal as user `user1` you will first get the Survey like you would expect in AAP, too.

=== Custom Templates

WIP

If you would like to use custom templates, you must link an external Source Control Management (SCM) system to self-service automation portal. This basically means you must generate a Personal Access Token for authentication. Self-service automation portal supports GitHub and GitLab SCMs.

Adding a Personal Access Token for the supported SMCs is documented https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/installing_self-service_automation_portal/self-service-preinstall-config_aap-self-service-install#self-service-generate-scm-tokens_self-service-preinstall-config[here]

Then follow the instructions for using custom https://docs.redhat.com/pt-br/documentation/red_hat_ansible_automation_platform/2.6/html/using_self-service_automation_portal/self-service-working-templates_aap-self-service-using[templates].



