== Setting Up RBAC

Up to now you've just used your AAP admin user who can see all Job Templates. But the main point of the Self-Service Portal is to enable users that don't need access to the AAP UI to execute Job Templates. This basically means we need unprivileged users with a limited view of the Job Templates, since we only want the user to see the Job Templates he is allowed to use.

=== Create an unprivileged user in AAP

Since users are synced from AAP to the Self-Service Portal, we first need a user with limited access to a Job Template. We assume you to have some experience with AAP adminstration so we'll just outline the steps you need to do. Let's get started:

* As admin in AAP create a Team `team1`  (you can of course get more creative...;-)
* Create a user `user1`
* Add the user to the team
* Duplicate the `Demo Job Template` to `Demo Job Template 2`
* Give the team `team1` execute rights on the template
* Check in AAP you can log in as the user and you can see and execute the Job Template

=== Test the user in the Self-Service Portal

Now switch to the Self-Service Portal UI as **user admin**.

* On the **Templates** page click `Sync now` aand select both `Organizations, Users, and Teams` and `Job Templates`.
* After the sync has finished, in an incognito tab **log in to the Portal as `user1`**

You should be able to log in but you won't see any Job Templates yet. This is because we have to setup RBAC in Self-Service Portal, too!

=== Setup RBAC Rules in Self-Service Portal

Go back to the browser where you are logged in as the Portal admin, then:

* From the side menu select **Administration -> RBAC**
* Click **Create** to create a new role.
* Give the role a name e.g. `team1`, then click **Next**
* In **Add users and groups** select the `team1` team, then click **Next**
* In **Add permission policies**, select the Catalog and Scaffolder plugins
* Expand the **Catalog** and **Scaffolder** plug-ins 

To allow users to view templates and execute jobs in Ansible Automation Platform, grant the following minimum permissions for the selected plug-ins by selecting the check box to the left of the permission names.

Catalog permissions:

* `catalog.entity.read`

Scaffolder permissions:

* `scaffolder.template.parameter.read`
* `scaffolder.template.step.read`
* `scaffolder.action.execute`
* `scaffolder.task.cancel`
* `scaffolder.task.create`
* `scaffolder.task.read`

* Click **Next**, review and click **Create**

[NOTE]
====
The scaffolder.task.read permission must be enabled so that users can view previous task runs in the History page in the self-service automation portal console.
====

When finished, your new role is included in the **All roles** list when you select **Administration -> RBAC** in the navigation pane in self-service automation portal.

=== Test Self-Service Portal with unprivileged User

No you are ready to test the unprivileged user! Back in the browser where you are logged in as user `user1`, refresh the browser window.

You should now see the duplicated Job Template you gave the user execute rights for in AAP and you should be able to launch it. Note the other template the user has no rights for won't show up!
